sudo: required

services:
  - docker

before_install: 
  - docker build -t radicalgolem/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true radicalgolem/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket-name: "elasticbeanstalk-ap-south-1-851725283401"
  bucket-path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"